// Une page par grande rubrique de l'appli EP Coaching. Tout est décrit
// d'après le code de l'appli (ep-coaching), jamais d'après une promesse :
// si une rubrique n'existe pas dans l'appli, elle n'a rien à faire ici.
// Règles : tutoiement, aucun tiret long, aucun prix, aucun chiffre inventé.

export const FEATURE_GROUPS = [
  { id: "suivi", title: "Ton suivi au quotidien", intro: "Ce que tout membre a dans sa poche : entraînement, nutrition, bilan, progression." },
  { id: "organisation", title: "T'organiser et tout retrouver", intro: "Agenda, notes, recherche instantanée : l'appli qui range ta tête." },
  { id: "coach", title: "Le coaching, côté coach", intro: "Tout ce qu'un coach en ligne utilise pour suivre ses clients et faire tourner son activité." },
  { id: "business", title: "Faire grandir ton activité", intro: "Contenu, stats, formations, ventes, équipe : le business du coach au même endroit." },
];

export const FEATURES = [
  // ── Suivi au quotidien ──────────────────────────────────────────────
  {
    slug: "aujourdhui",
    group: "suivi",
    icon: "home",
    name: "Aujourd'hui",
    for: "Membres et coachs",
    metaTitle: "Aujourd'hui : ta journée d'entraînement et de nutrition en un écran",
    metaDesc: "L'écran Aujourd'hui d'EP Coaching te montre ce que tu as à faire : bilan, repas, séance, pas. Tu coches au fur et à mesure, rien ne se perd.",
    title: "Ta journée, <span class=\"accent\">en un seul écran</span>",
    lead: "Tu ouvres l'appli, tu sais quoi faire. Bilan, repas, séance, pas : tout ce qui compte aujourd'hui est là, dans l'ordre, et tu coches au fur et à mesure.",
    summary: "Ton point de départ chaque matin : bilan, repas, séance et pas du jour.",
    points: [
      { icon: "clipboard", t: "Les tâches du jour", d: "Bilan du matin, bilan du soir, repas, séance : chaque chose à faire apparaît avec son état. Ce qui est fait est coché, ce qui reste saute aux yeux." },
      { icon: "dumbbell", t: "La séance prévue", d: "Tu vois la séance du jour, ce qu'il faut prévoir (accessoires, créneau utile) et tu la lances en un geste. Jour de repos ? L'écran te le dit aussi." },
      { icon: "target", t: "Tes anneaux de constance", d: "Pas, nutrition et régularité de la semaine sous forme d'anneaux, pour voir en un coup d'œil si tu tiens le rythme." },
      { icon: "sliders", t: "Seulement ce qui te sert", d: "L'accueil s'adapte à ce que tu as choisi dans Mon appli : si tu ne suis pas ton sommeil, il n'en parle pas." },
    ],
    stepsTitle: "Comment ça se passe",
    steps: [
      { t: "Le matin", d: "Tu ouvres l'appli : ton bilan du matin (poids, nuit) t'attend en haut de l'écran." },
      { t: "Pendant la journée", d: "Tu notes tes repas, tu lances ta séance, tes pas montent. Chaque action coche sa case." },
      { t: "Le soir", d: "Ton bilan du soir boucle la journée. Tu vois ce qui a été tenu, sans culpabiliser pour le reste." },
    ],
    coachNote: "Côté coach, l'écran Aujourd'hui devient un poste de pilotage : alertes clients, messages non lus, ta journée et tes raccourcis selon tes objectifs.",
    faq: [
      { q: "Est-ce que l'écran Aujourd'hui est le même pour tout le monde ?", a: "Non. Il se construit avec ce que tu suis vraiment (réglable dans Mon appli) et, si tu as un coach, avec ce qu'il t'a programmé." },
      { q: "J'ai raté mon bilan hier, je peux le rattraper ?", a: "Oui. Le bilan permet de choisir une date passée pour compléter un jour oublié." },
    ],
    related: ["bilan", "entrainement", "nutrition", "personnalisation"],
    help: ["premiers-pas-membre", "remplir-son-bilan"],
  },
  {
    slug: "entrainement",
    group: "suivi",
    icon: "dumbbell",
    name: "Entraînement",
    for: "Membres et coachs",
    metaTitle: "Programme de musculation et logbook : ta séance guidée série par série",
    metaDesc: "Programme sur mesure, séance guidée, charges notées série par série, records et historique complet. Le logbook d'EP Coaching suit chaque séance.",
    title: "Ton programme et ton logbook, <span class=\"accent\">sans carnet</span>",
    lead: "Tu lances ta séance, l'appli te guide exercice par exercice. Tu notes tes charges, tu vois ce que tu as fait la dernière fois, tu bats tes records.",
    summary: "Programme, séance guidée, charges et records : chaque série est gardée.",
    points: [
      { icon: "dumbbell", t: "Séance guidée", d: "Exercice après exercice, avec les cibles série par série (répétitions, charge, effort) et un temps de repos qui ne bloque jamais l'écran." },
      { icon: "chart", t: "Records et historique", d: "Tes meilleures performances sont repérées toutes seules et tout ton historique reste consultable, séance après séance." },
      { icon: "book", t: "Bibliothèque d'exercices", d: "Chaque exercice avec ses consignes, les variantes et le matériel à prévoir. Tu sais quoi faire même sur une machine que tu ne connais pas." },
      { icon: "note", t: "Notes qui restent", d: "Une sensation, un réglage de machine, une douleur à surveiller : tes notes d'exercice te suivent à la séance suivante." },
    ],
    stepsTitle: "Une séance, du début à la fin",
    steps: [
      { t: "Tu ouvres Training", d: "La séance du jour est prête. Tu vois le matériel à prévoir avant même d'arriver à la salle." },
      { t: "Tu enchaînes", d: "Pour chaque série, tu notes la charge et les répétitions. La dernière séance est affichée à côté, pour savoir quoi battre." },
      { t: "Tu termines", d: "Les records sont mis à jour, la séance rejoint ton historique et ton coach la voit s'il te suit." },
    ],
    coachNote: "Le coach construit ses programmes avec des modèles réutilisables, la périodisation par cycles et des repères de variété d'exercices, puis les assigne à ses clients.",
    faq: [
      { q: "Je n'ai pas de coach, j'ai quand même un programme ?", a: "Oui, l'appli peut te proposer un programme adapté à ton niveau et à ton matériel. Avec un coach, c'est lui qui le construit pour toi." },
      { q: "J'ai terminé une séance par erreur, je peux la rouvrir ?", a: "Oui, une séance terminée par erreur peut être rouverte depuis le logbook." },
      { q: "Est-ce que ça marche à la maison ?", a: "Oui. Le programme tient compte du matériel disponible, que tu t'entraînes en salle ou chez toi." },
    ],
    related: ["aujourdhui", "progression", "bilan", "clients"],
    help: ["lancer-sa-seance", "records-et-historique"],
  },
  {
    slug: "nutrition",
    group: "suivi",
    icon: "apple",
    name: "Nutrition",
    for: "Membres et coachs",
    metaTitle: "Suivi nutrition et plan alimentaire : calories et macros sans prise de tête",
    metaDesc: "Un tracker nutrition construit autour de ton plan : repas prévus, alternatives, recettes, aliments filtrés selon ton régime. Tes calories remontent seules dans ton bilan.",
    title: "Ta nutrition, <span class=\"accent\">construite autour de ton plan</span>",
    lead: "Tu ne pars pas d'une page blanche : tes repas prévus sont déjà là. Tu valides ce que tu as mangé, tu remplaces si besoin, et tes calories remontent seules dans ton bilan.",
    summary: "Plan alimentaire, repas alternatifs, recettes et calories qui remontent toutes seules.",
    points: [
      { icon: "clipboard", t: "Le plan d'abord", d: "Tes repas du jour sont proposés à partir de ton plan. Un repas mangé tel quel se valide en un geste." },
      { icon: "sliders", t: "De vrais choix", d: "Les repas alternatifs sont présentés comme de vrais choix distincts, pour varier sans sortir de tes objectifs." },
      { icon: "apple", t: "Aliments et régimes", d: "Chaque aliment porte ses repères diététiques et allergènes : le choix d'aliments se filtre selon ton régime (végétarien, sans gluten, et d'autres)." },
      { icon: "book", t: "Recettes", d: "Une base de recettes accessible depuis le tracker, avec des filtres temps et budget, et des portions pour préparer tes repas à l'avance." },
    ],
    stepsTitle: "Au quotidien",
    steps: [
      { t: "Tu regardes ce qui est prévu", d: "Les repas du jour sont listés à partir de ton plan." },
      { t: "Tu valides ou tu remplaces", d: "Mangé comme prévu : un geste. Autre chose : tu cherches l'aliment ou la recette et tu l'ajoutes." },
      { t: "Ton bilan se remplit seul", d: "Les calories et macros du jour remontent dans ton bilan, rien à retaper." },
    ],
    coachNote: "Le coach construit le plan de chaque client, voit les repas enregistrés et peut importer un repas dans le plan en un clic.",
    faq: [
      { q: "Faut-il peser tous ses aliments ?", a: "Non. Partir du plan et valider les repas prévus évite de tout peser au quotidien. Peser reste utile au début pour apprendre les portions." },
      { q: "Je mange souvent la même chose, c'est pratique ?", a: "Oui : un repas déjà prévu ou déjà enregistré se valide en un geste." },
      { q: "L'appli gère-t-elle les régimes particuliers ?", a: "Les aliments portent des repères de régime et d'allergènes, ce qui permet de filtrer les choix. Pour un besoin médical, ton coach ou un professionnel de santé reste la référence." },
    ],
    related: ["bilan", "aujourdhui", "bibliotheque", "entrainement"],
    help: ["suivre-sa-nutrition", "remplir-son-bilan"],
  },
  {
    slug: "bilan",
    group: "suivi",
    icon: "clipboard",
    name: "Bilan du jour",
    for: "Membres et coachs",
    metaTitle: "Bilan quotidien : poids, sommeil, pas et forme du jour en 30 secondes",
    metaDesc: "Le bilan du jour EP Coaching : poids du matin, nuit, pas, ressenti, énergie, moral, hydratation, courbatures, fréquence cardiaque au repos et VFC. Tu ne suis que ce que tu choisis.",
    title: "Ton bilan du jour, <span class=\"accent\">en 30 secondes</span>",
    lead: "Le matin ton poids et ta nuit, le soir tes pas et ton ressenti. Quelques touches par jour, et tu as enfin des données fiables sur toi.",
    summary: "Poids, sommeil, pas, énergie, moral : les bons chiffres, en quelques touches.",
    points: [
      { icon: "clipboard", t: "Matin et soir", d: "Le bilan est découpé en deux moments courts : ce qui se mesure au réveil, et ce qui se mesure en fin de journée." },
      { icon: "heart", t: "Forme du jour", d: "Énergie, moral, hydratation, courbatures, et si tu as une montre : fréquence cardiaque au repos et variabilité cardiaque. À activer si ça t'intéresse." },
      { icon: "chart", t: "Tendances", d: "Ton poids se lit en tendance, pas au jour le jour. Une alerte te prévient aussi quand ta dette de sommeil s'accumule." },
      { icon: "sliders", t: "Seulement tes suivis", d: "Tu choisis ce que tu suis dans Mon appli. Le bilan ne te pose que ces questions-là." },
    ],
    stepsTitle: "Pourquoi ça marche",
    steps: [
      { t: "C'est court", d: "Quelques champs, pas un questionnaire. C'est ce qui permet de le tenir tous les jours." },
      { t: "C'est relié", d: "Les calories viennent du tracker nutrition, les pas de ta journée : tu ne tapes pas deux fois la même chose." },
      { t: "C'est lu", d: "Si tu as un coach, il voit tes bilans et s'en sert pour ajuster ton plan." },
    ],
    coachNote: "Le coach remplit aussi son propre bilan dans son espace Moi, avec exactement les mêmes outils que ses clients.",
    faq: [
      { q: "Je dois tout remplir tous les jours ?", a: "Non. Remplis ce que tu peux. La régularité compte plus que l'exhaustivité, et tu peux rattraper un jour oublié." },
      { q: "Je n'ai pas de montre connectée, c'est grave ?", a: "Pas du tout. La fréquence cardiaque au repos et la variabilité cardiaque sont optionnelles, désactivées par défaut." },
    ],
    related: ["aujourdhui", "progression", "semaine", "nutrition"],
    help: ["remplir-son-bilan", "choisir-ses-suivis"],
  },
  {
    slug: "progression",
    group: "suivi",
    icon: "image",
    name: "Photos et mensurations",
    for: "Membres et coachs",
    metaTitle: "Photos de progression et mensurations : voir ta transformation",
    metaDesc: "Photos de progression avec poses guidées, mensurations, taux de masse grasse et courbes d'évolution. Ton avant et après, rangé et privé.",
    title: "Voir ta progression, <span class=\"accent\">même quand la balance ne bouge pas</span>",
    lead: "La balance ment souvent. Les photos et les mensurations, beaucoup moins. EP Coaching range tout, au même endroit, pour comparer semaine après semaine.",
    summary: "Photos guidées, mensurations, masse grasse et courbes d'évolution.",
    points: [
      { icon: "image", t: "Photos guidées", d: "Des poses de progression standard pour comparer ce qui est comparable. En préparation de compétition, les poses de ta catégorie et un compte à rebours." },
      { icon: "target", t: "Mensurations", d: "Tour de taille, de hanches, de bras et d'autres : tu ne suis que ceux qui t'intéressent." },
      { icon: "chart", t: "Masse grasse", d: "Tu peux noter ton taux de masse grasse et la méthode utilisée, pour comparer des mesures cohérentes entre elles." },
      { icon: "lock", t: "Privé par défaut", d: "Tes photos sont stockées dans un espace privé. Seul ton coach, si tu en as un, peut les voir." },
    ],
    stepsTitle: "La bonne routine",
    steps: [
      { t: "Même jour, même lumière", d: "Une fois par semaine ou toutes les deux semaines, dans les mêmes conditions." },
      { t: "Mêmes poses", d: "L'appli te guide pose par pose pour que tes comparaisons aient un sens." },
      { t: "Tu compares", d: "Côte à côte, avec tes mensurations et ta courbe de poids pour lire la vraie tendance." },
    ],
    faq: [
      { q: "Qui peut voir mes photos ?", a: "Toi, et ton coach si tu es accompagné. Elles ne sont jamais publiques." },
      { q: "Je prépare une compétition, l'appli m'aide ?", a: "Oui : poses de ta catégorie, guide de posing et compte à rebours jusqu'à la date." },
    ],
    related: ["bilan", "road-map", "entrainement"],
    help: ["prendre-ses-photos"],
  },
  {
    slug: "road-map",
    group: "suivi",
    icon: "map",
    name: "Road Map",
    for: "Membres et coachs",
    metaTitle: "Road Map : tes objectifs et les étapes pour les atteindre",
    metaDesc: "La Road Map EP Coaching découpe ton objectif en phases : prise de muscle, sèche, maintien. Tu sais où tu en es et ce qui vient ensuite.",
    title: "Ton objectif, <span class=\"accent\">découpé en étapes</span>",
    lead: "Un objectif flou ne se tient pas. La Road Map le découpe en phases claires, avec la phase active en évidence et ce qui vient après.",
    summary: "Tes objectifs en phases, avec la phase active toujours visible.",
    points: [
      { icon: "map", t: "Des phases claires", d: "Prise de muscle, sèche, maintien, reprise : chaque phase a son objectif et sa durée." },
      { icon: "target", t: "La phase active", d: "Un résumé de la phase en cours et de tes objectifs, toujours visible." },
      { icon: "chart", t: "Relié à ton suivi", d: "Tes bilans et ta progression donnent du concret à chaque étape." },
    ],
    faq: [
      { q: "Qui crée ma Road Map ?", a: "Si tu as un coach, c'est lui qui la construit avec toi. Sinon, tu poses toi-même tes objectifs et tes étapes." },
    ],
    related: ["progression", "semaine", "bilan"],
    help: [],
  },
  {
    slug: "semaine",
    group: "suivi",
    icon: "week",
    name: "Ma semaine",
    for: "Membres et coachs",
    metaTitle: "Revue de la semaine : ce qui a marché, ce qui a coincé",
    metaDesc: "Chaque semaine, EP Coaching résume ce que tu as noté : poids, séances, nutrition, sommeil, pas. Une revue claire pour ajuster la semaine suivante.",
    title: "Ta semaine, <span class=\"accent\">résumée pour toi</span>",
    lead: "Pas besoin de tout relire. Ma semaine rassemble ce que tu as déjà noté et te montre la tendance : ce qui a tenu, ce qui a glissé, quoi ajuster.",
    summary: "Le résumé de ta semaine, construit à partir de ce que tu as déjà noté.",
    points: [
      { icon: "week", t: "Rien à ressaisir", d: "Tout vient de ce que tu as noté ailleurs dans l'appli : bilans, séances, repas, pas." },
      { icon: "sliders", t: "Tes suivis seulement", d: "La revue n'affiche que ce que tu as choisi de suivre dans Mon appli." },
      { icon: "message", t: "Le check-in avec ton coach", d: "Si tu es coaché, ton bilan de la semaine part à ton coach, qui te répond directement dans l'appli." },
    ],
    faq: [
      { q: "La revue de la semaine est-elle réservée aux clients coachés ?", a: "Non, elle est ouverte à tous les membres. Seul le check-in hebdomadaire, lu et répondu par un coach, demande d'être accompagné." },
    ],
    related: ["bilan", "messages", "road-map"],
    help: ["check-in-hebdo"],
  },
  {
    slug: "messages",
    group: "suivi",
    icon: "message",
    name: "Coach et messages",
    for: "Clients coachés",
    metaTitle: "Messagerie coach et check-in hebdo : ton coach, dans ta poche",
    metaDesc: "Messagerie directe avec ton coach, check-in hebdomadaire, tâches et coaching live : l'accompagnement humain d'EP Coaching, au même endroit que ton suivi.",
    title: "Ton coach, <span class=\"accent\">au même endroit que ton suivi</span>",
    lead: "Quand tu es accompagné, tout passe par l'appli : tes messages, ton check-in de la semaine, les tâches que ton coach te donne et vos lives.",
    summary: "Messagerie, check-in hebdo, tâches et lives avec ton coach.",
    points: [
      { icon: "message", t: "Messagerie directe", d: "Tu écris à ton coach quand tu en as besoin, avec photos et vidéos de ta technique si besoin." },
      { icon: "clipboard", t: "Check-in hebdo", d: "Une fois par semaine, ton bilan de la semaine part à ton coach, qui te répond dans l'appli." },
      { icon: "note", t: "Tes tâches", d: "Les actions que ton coach te demande, listées et datées." },
      { icon: "video", t: "Coaching live", d: "Appels 1-to-1, audits, ateliers et sessions de questions, directement depuis l'appli." },
    ],
    faq: [
      { q: "Je n'ai pas encore de coach, j'ai accès à la messagerie ?", a: "La messagerie coach, le check-in hebdo, les tâches et les lives sont réservés aux membres accompagnés. Tout le reste de l'appli est accessible gratuitement." },
    ],
    related: ["semaine", "live", "clients"],
    help: ["check-in-hebdo", "trouver-un-coach"],
  },
  {
    slug: "communaute",
    group: "suivi",
    icon: "heart",
    name: "Communauté",
    for: "Membres et coachs",
    metaTitle: "Communauté EP Coaching : victoires, questions et entraide",
    metaDesc: "Partage tes victoires, pose tes questions, lis le mot du coach et suis le classement. La communauté EP Coaching pour ne pas avancer seul.",
    title: "Tu n'avances <span class=\"accent\">pas seul</span>",
    lead: "Une communauté de gens qui bossent comme toi : on partage ses victoires, on pose ses questions, on s'encourage.",
    summary: "Victoires, questions, mot du coach et classement.",
    points: [
      { icon: "sparkles", t: "Victoires", d: "Un record, un kilo, une semaine tenue : tu partages, les autres te félicitent avec un Bravo." },
      { icon: "help", t: "Questions", d: "Tu poses ta question, la communauté et les coachs répondent." },
      { icon: "message", t: "Mot du coach", d: "Les messages du coach à toute sa communauté." },
      { icon: "chart", t: "Classement", d: "Des points pour ta régularité. Tu peux t'en retirer à tout moment dans tes réglages de confidentialité." },
    ],
    faq: [
      { q: "Je peux rester discret ?", a: "Oui. Tu peux te retirer du classement depuis la rubrique Confidentialité de tes paramètres." },
    ],
    related: ["formations", "messages"],
    help: ["confidentialite-membre"],
  },
  {
    slug: "formations",
    group: "business",
    icon: "cap",
    name: "Formations",
    for: "Membres et coachs",
    metaTitle: "Formations en ligne : suivre, créer et vendre ta formation de coach",
    metaDesc: "Suis des formations vidéo dans l'appli, ou crée et vends la tienne si tu es coach : sections, vidéos YouTube, accès inclus ou payant, accès donné en un clic.",
    title: "Apprendre, et <span class=\"accent\">transmettre</span>",
    lead: "Côté membre, tu suis des formations vidéo à ton rythme. Côté coach, tu crées la tienne, tu la donnes à tes clients ou tu la vends.",
    summary: "Suivre des formations, ou créer et vendre la tienne.",
    points: [
      { icon: "cap", t: "Créer en quelques minutes", d: "Sections, leçons, vidéos YouTube (même non répertoriées) : ta formation est structurée comme un vrai cours." },
      { icon: "lock", t: "Incluse ou payante", d: "Tu choisis : incluse pour tes clients, ou payante avec ton propre lien de paiement. Après un achat, tu donnes l'accès en un clic." },
      { icon: "chart", t: "Progression suivie", d: "Chaque membre voit où il en est dans chaque formation." },
    ],
    stepsTitle: "Créer ta formation",
    steps: [
      { t: "Nouvelle formation", d: "Dans Business, ouvre Mes formations puis « Nouvelle formation »." },
      { t: "Ajoute tes contenus", d: "Tes sections et tes vidéos YouTube, puis publie." },
      { t: "Choisis l'accès", d: "Incluse pour tes clients, ou payante avec ton lien de paiement." },
    ],
    faq: [
      { q: "Je dois héberger mes vidéos ?", a: "Non, tu utilises YouTube, même en non répertorié. L'appli s'occupe de la structure et des accès." },
      { q: "EP Coaching prend une commission sur mes ventes de formation ?", a: "Tu vends avec ton propre lien de paiement : l'argent arrive chez toi." },
    ],
    related: ["studio", "clients", "business"],
    help: ["creer-sa-formation"],
  },
  {
    slug: "bibliotheque",
    group: "suivi",
    icon: "book",
    name: "Bibliothèque",
    for: "Membres et coachs",
    metaTitle: "Recettes, exercices, guides et science : la bibliothèque EP Coaching",
    metaDesc: "Recettes du monde et de terroir, exercices et salles, guides pratiques et une section science expliquée simplement. Tout est dans l'appli.",
    title: "Tout ce qu'il faut savoir, <span class=\"accent\">rangé au même endroit</span>",
    lead: "Recettes, exercices, guides pratiques et science expliquée simplement : une bibliothèque complète, reliée à ton suivi.",
    summary: "Recettes, exercices, guides pratiques et science expliquée simplement.",
    points: [
      { icon: "apple", t: "Recettes", d: "Des recettes du monde et de nos terroirs, filtrables par temps et budget, avec les portions pour cuisiner à l'avance." },
      { icon: "dumbbell", t: "Exercices et salles", d: "Chaque exercice expliqué, avec ses variantes et le matériel à prévoir." },
      { icon: "book", t: "Guides pratiques", d: "Plus de 1000 guides courts et concrets sur l'entraînement, la nutrition, la récupération et le mental." },
      { icon: "search", t: "Science", d: "La recherche en sport et nutrition, traduite en conseils clairs, sans jargon." },
    ],
    faq: [
      { q: "Les guides sont-ils gratuits ?", a: "Oui, les guides pratiques sont gratuits. Tu peux les parcourir sur ce site dans la rubrique Ressources." },
    ],
    related: ["nutrition", "entrainement", "formations"],
    help: [],
    extraCta: { label: "Parcourir les guides gratuits", href: "/ressources/" },
  },

  // ── Organisation ────────────────────────────────────────────────────
  {
    slug: "agenda",
    group: "organisation",
    icon: "calendar",
    name: "Agenda",
    for: "Membres et coachs",
    metaTitle: "Agenda intelligent : ta semaine type qui se réorganise toute seule",
    metaDesc: "Un agenda où chaque bloc ouvre la bonne page (repas, séance, scripts) et où un retard décale toute la suite de la journée en un geste.",
    title: "Un agenda <span class=\"accent\">qui suit ta vraie journée</span>",
    lead: "Tu construis ta semaine type une fois. Quand la journée dérape, tu décales un bloc et toute la suite suit. Et chaque bloc t'emmène au bon endroit de l'appli.",
    summary: "Semaine type, blocs reliés à la bonne page, retard rattrapé en un geste.",
    points: [
      { icon: "calendar", t: "Semaine type", d: "Repas, séances, travail, contenu : tu poses tes blocs une fois, ils se répètent chaque semaine." },
      { icon: "bolt", t: "Retard rattrapé", d: "Un bloc a sauté ? « Commencer maintenant » ou décale de 15, 30 ou 60 minutes : toute la suite de la journée se décale avec." },
      { icon: "arrow", t: "Le bon endroit", d: "Un bloc repas ouvre ta nutrition, un bloc séance ton programme, un bloc contenu tes scripts." },
      { icon: "clipboard", t: "Aujourd'hui seulement", d: "Un changement ponctuel ne touche pas ta semaine type." },
    ],
    stepsTitle: "Réorganiser une journée en retard",
    steps: [
      { t: "Touche le bloc qui a sauté", d: "Sa fiche s'ouvre avec les actions possibles." },
      { t: "Décale ou commence maintenant", d: "Toute la suite de la journée suit automatiquement." },
      { t: "Va au bon endroit", d: "Le bouton en haut de la fiche t'emmène directement au repas, à la séance ou au script concerné." },
    ],
    faq: [
      { q: "Décaler un bloc modifie-t-il toute ma semaine ?", a: "Seulement si tu le demandes. Par défaut, « Aujourd'hui seulement » ne touche pas à ta semaine type." },
      { q: "Je reçois un rappel avant chaque bloc ?", a: "Oui si tu as activé les notifications, avec des heures de silence réglables pour la nuit." },
    ],
    related: ["aujourdhui", "notes", "appli-mobile"],
    help: ["reorganiser-sa-journee", "activer-les-notifications"],
  },
  {
    slug: "notes",
    group: "organisation",
    icon: "note",
    name: "Notes",
    for: "Membres et coachs",
    metaTitle: "Notes façon Obsidian : tags, liens entre notes, captures et recherche",
    metaDesc: "Écris ou dicte une idée, ajoute des #tags, relie tes notes avec [[liens]], colle une capture d'écran. Tes notes EP Coaching se rangent seules et se retrouvent en un geste.",
    title: "Tout noter, <span class=\"accent\">tout retrouver</span>",
    lead: "Une idée de contenu, une remarque sur un client, une sensation à l'entraînement : tu la notes en deux secondes, elle se range seule, tu la retrouves quand tu en as besoin.",
    summary: "Tags, liens entre notes, captures, dictée et recherche instantanée.",
    points: [
      { icon: "note", t: "Écrire ou dicter", d: "Tape, dicte, colle un lien ou ajoute une capture d'écran. Une note rapide est accessible de partout dans l'appli." },
      { icon: "sparkles", t: "Des #tags qui rangent", d: "Ajoute #reel, #client ou #idée : les notes se classent seules, et une note qui parle d'un tag existant le reçoit automatiquement." },
      { icon: "plug", t: "Des notes reliées", d: "Relie deux notes avec [[Titre de la note]], comme dans Obsidian. Ton savoir devient un réseau, pas une pile." },
      { icon: "search", t: "Recherche instantanée", d: "La recherche retrouve tout, même depuis la loupe de l'appli." },
    ],
    stepsTitle: "Prendre une note",
    steps: [
      { t: "Ouvre Notes ou le bouton de note rapide", d: "Il est disponible partout dans l'appli." },
      { t: "Écris, dicte ou colle", d: "Texte, lien, capture d'écran : tout est accepté." },
      { t: "Ajoute un #tag ou un [[lien]]", d: "La note se range et se relie toute seule." },
    ],
    faq: [
      { q: "Mes notes sont-elles privées ?", a: "Oui. Tes notes et tes captures sont privées, seul ton compte y a accès." },
      { q: "Je peux importer mes notes Notion ?", a: "Oui, grâce au connecteur Claude : tu demandes à Claude d'importer une page Notion dans tes notes EP Coaching." },
    ],
    related: ["claude-notion", "recherche", "agenda"],
    help: ["prendre-des-notes", "relier-claude-et-notion"],
  },
  {
    slug: "recherche",
    group: "organisation",
    icon: "search",
    name: "Recherche et réponses rapides",
    for: "Membres et coachs",
    metaTitle: "Réponses rapides : ton poids, tes calories ou tes leads en un geste",
    metaDesc: "Tape « poids », « calories », « sommeil » ou « leads » dans la loupe : EP Coaching affiche le chiffre tout de suite. La recherche retrouve aussi notes, recettes et clients.",
    title: "L'info que tu cherches, <span class=\"accent\">en un geste</span>",
    lead: "Tu touches la loupe, tu tapes un mot, le chiffre s'affiche. Pas besoin de savoir dans quel menu il se cache.",
    summary: "Tape un mot, le chiffre s'affiche : poids, calories, séances, leads, paie.",
    points: [
      { icon: "search", t: "Réponses immédiates", d: "« poids », « calories », « sommeil », « pas », « séances » : le chiffre de ta semaine s'affiche tout de suite." },
      { icon: "briefcase", t: "Côté coach", d: "« clients », « bilans », « leads », « paie » : l'essentiel de ton activité sans ouvrir un tableau." },
      { icon: "note", t: "Tout le reste", d: "Notes, recettes, clients, pages de l'appli : la recherche tolère les fautes de frappe." },
    ],
    faq: [
      { q: "Où est la loupe ?", a: "En bas à droite de l'écran, ou en haut de la page Plus. Sur ordinateur, le raccourci Ctrl+K (ou Cmd+K) l'ouvre aussi." },
    ],
    related: ["notes", "aujourdhui", "pilotage"],
    help: ["trouver-une-info"],
  },
  {
    slug: "claude-notion",
    group: "organisation",
    icon: "plug",
    name: "Connecteur Claude et Notion",
    for: "Membres et coachs",
    metaTitle: "Connecteur Claude (MCP) : relie EP Coaching à Claude et à Notion",
    metaDesc: "Ajoute EP Coaching comme connecteur dans Claude : importe tes pages Notion dans tes notes, cherche dans tes notes, récupère tes chiffres de la semaine en conversation.",
    title: "EP Coaching dans <span class=\"accent\">Claude</span>",
    lead: "Tu travailles déjà avec Claude et Notion ? Branche EP Coaching comme connecteur : Claude peut ajouter des notes, chercher dedans et lire tes chiffres de la semaine.",
    summary: "Branche l'appli à Claude : notes, recherche et chiffres de la semaine en conversation.",
    points: [
      { icon: "plug", t: "Un connecteur personnel", d: "Tu génères ton adresse de connecteur dans Notes. Elle est personnelle et tu peux la révoquer à tout moment." },
      { icon: "note", t: "Notion vers tes notes", d: "Demande à Claude : « importe ma page Notion Idées dans mes notes EP Coaching »." },
      { icon: "search", t: "Chercher et résumer", d: "Claude peut chercher dans tes notes, lister les plus récentes et résumer tes chiffres de la semaine." },
      { icon: "lock", t: "Sous ton contrôle", d: "La clé n'est jamais stockée en clair et ne donne accès qu'à ton propre compte." },
    ],
    stepsTitle: "Le brancher en 3 étapes",
    steps: [
      { t: "Génère ton adresse", d: "Dans Notes, ouvre « Relier Claude et Notion » et génère ton adresse de connecteur." },
      { t: "Ajoute-la dans Claude", d: "Sur claude.ai : Réglages, Connecteurs, Ajouter un connecteur personnalisé, puis colle l'adresse." },
      { t: "Utilise-le", d: "Dans une conversation, active EP Coaching (et Notion), puis demande ce dont tu as besoin." },
    ],
    faq: [
      { q: "Faut-il un abonnement Claude ?", a: "Les connecteurs personnalisés dépendent de ton offre Claude. Vérifie dans les réglages de ton compte Claude." },
      { q: "Comment couper l'accès ?", a: "Révoque la clé dans Notes : le connecteur cesse immédiatement de fonctionner." },
    ],
    related: ["notes", "recherche"],
    help: ["relier-claude-et-notion"],
  },
  {
    slug: "personnalisation",
    group: "organisation",
    icon: "sliders",
    name: "Mon appli",
    for: "Membres et coachs",
    metaTitle: "Personnalise ton appli : garde seulement ce qui te sert",
    metaDesc: "Réponds à quelques questions dans Mon appli : EP Coaching n'affiche que les suivis et les outils que tu utilises. Tu peux changer à tout moment.",
    title: "Une appli <span class=\"accent\">à ta mesure</span>",
    lead: "Tout le monde ne suit pas la même chose. Mon appli te pose quelques questions et ne garde que ce qui te sert : le menu, le bilan et l'accueil s'adaptent.",
    summary: "Quelques questions, et l'appli ne garde que ce qui te sert.",
    points: [
      { icon: "sliders", t: "Tes suivis", d: "Poids, mensurations, sommeil, pas, masse grasse, forme du jour, compétition : tu coches ce que tu suis." },
      { icon: "briefcase", t: "Ta façon de coacher", d: "Coach solo ou entreprise avec une équipe : les outils business s'adaptent à ton parcours." },
      { icon: "home", t: "Un menu épuré", d: "Ce que tu n'utilises pas disparaît du menu, de ton bilan et de ton accueil." },
    ],
    faq: [
      { q: "Je peux changer d'avis ?", a: "Oui, à tout moment dans Mon appli. Rien n'est supprimé, les rubriques sont simplement masquées." },
    ],
    related: ["aujourdhui", "bilan", "appli-mobile"],
    help: ["choisir-ses-suivis"],
  },
  {
    slug: "appli-mobile",
    group: "organisation",
    icon: "phone",
    name: "Sur ton téléphone",
    for: "Membres et coachs",
    metaTitle: "EP Coaching sur ton téléphone : installation, notifications, raccourcis",
    metaDesc: "Installe EP Coaching sur ton écran d'accueil, active les notifications avec heures de silence, utilise les raccourcis et règle la taille du texte.",
    title: "Pensée pour <span class=\"accent\">ton téléphone</span>",
    lead: "EP Coaching se range sur ton écran d'accueil comme une appli classique. Cinq onglets, une page Plus, des raccourcis : tout se fait au pouce.",
    summary: "Installation, notifications, raccourcis et accessibilité.",
    points: [
      { icon: "phone", t: "Sur l'écran d'accueil", d: "Installe l'appli depuis Safari ou Chrome en quelques secondes, sans passer par un store." },
      { icon: "bolt", t: "Notifications", d: "Rappels de bilan, de séance, de blocs d'agenda, avec des heures de silence pour la nuit." },
      { icon: "arrow", t: "Raccourcis", d: "Appui long sur l'icône : note rapide, bilan, agenda ou recherche en un geste." },
      { icon: "sliders", t: "Accessibilité", d: "Taille du texte et animations réglables dans les paramètres." },
    ],
    faq: [
      { q: "Il faut télécharger l'appli sur un store ?", a: "Pas besoin : l'appli s'installe directement depuis ton navigateur sur ton écran d'accueil." },
      { q: "Ça marche sur ordinateur ?", a: "Oui, l'appli fonctionne aussi dans le navigateur de ton ordinateur, avec la même recherche et les mêmes données." },
    ],
    related: ["personnalisation", "agenda", "recherche"],
    help: ["installer-lappli", "activer-les-notifications"],
  },

  // ── Coach ───────────────────────────────────────────────────────────
  {
    slug: "clients",
    group: "coach",
    icon: "users",
    name: "Gestion des clients",
    for: "Coachs",
    metaTitle: "Logiciel de suivi client pour coach sportif : bilans, programmes, priorités",
    metaDesc: "Chaque client avec ses bilans, son programme, sa nutrition et vos échanges. Priorités, boîte de réception unique, modèles de programmes et relances automatiques.",
    title: "Tous tes clients, <span class=\"accent\">et qui a besoin de toi en premier</span>",
    lead: "Fini les tableurs, les notes éparpillées et les messages perdus. Chaque client a sa fiche complète, et l'appli te dit qui suivre en priorité aujourd'hui.",
    summary: "Fiches clients, priorités, boîte de réception unique et modèles de programmes.",
    points: [
      { icon: "users", t: "Fiche client complète", d: "Bilans, programme, plan nutrition, photos, check-ins, échanges : tout au même endroit." },
      { icon: "target", t: "Qui a besoin de moi", d: "Les priorités remontent les clients qui décrochent ou qui attendent une réponse." },
      { icon: "clipboard", t: "Boîte de réception unique", d: "Bilans, demandes de correction technique et photos qui attendent une réponse, triés par ancienneté." },
      { icon: "book", t: "Modèles et contraintes", d: "Bibliothèque de modèles de programmes, et un référentiel des contraintes (blessures, grossesse, pathologies) pour construire un programme adapté." },
      { icon: "bolt", t: "Assistant de relance", d: "Chaque jour, ton assistant repère les clients à risque et prépare les relances." },
      { icon: "lock", t: "Cloisonnement total", d: "Chaque coach ne voit que ses propres clients. Les données d'un client ne sont jamais visibles d'un autre coach." },
    ],
    stepsTitle: "Ta routine de coach",
    steps: [
      { t: "Le matin", d: "L'écran Aujourd'hui te montre les alertes et les messages non lus." },
      { t: "La boîte de réception", d: "Tu traites bilans et demandes par ordre d'ancienneté, sans ouvrir chaque fiche." },
      { t: "Les ajustements", d: "Programme, plan nutrition ou tâches : tu ajustes depuis la fiche client." },
    ],
    faq: [
      { q: "Mes clients doivent-ils payer l'appli ?", a: "Non. Tes clients utilisent l'appli dans le cadre de ton accompagnement." },
      { q: "Je peux importer mes clients actuels ?", a: "Tu les invites avec ton code ou ton lien d'invitation : ils créent leur compte et arrivent directement dans ton espace." },
      { q: "Les clients d'un coach sont-ils visibles par les autres coachs ?", a: "Jamais. Chaque coach n'a accès qu'à ses propres clients." },
    ],
    related: ["studio", "live", "pilotage", "entrainement"],
    help: ["premiers-pas-coach", "inviter-ses-clients"],
  },
  {
    slug: "live",
    group: "coach",
    icon: "video",
    name: "Coaching live",
    for: "Coachs et clients coachés",
    metaTitle: "Coaching live : appels 1-to-1, audits, ateliers et webinaires",
    metaDesc: "Planifie tes appels 1-to-1, audits, check-ins hebdo, ateliers, webinaires et sessions de questions directement dans EP Coaching.",
    title: "Tes lives, <span class=\"accent\">dans la même appli</span>",
    lead: "Appels individuels, audits, ateliers de groupe : tu planifies, ton client rejoint depuis l'appli, sans jongler entre les outils.",
    summary: "1-to-1, audits, check-ins, ateliers, webinaires et questions-réponses.",
    points: [
      { icon: "video", t: "Sept formats", d: "1-to-1, audit, check-in hebdo, accès direct, atelier, webinaire et questions-réponses." },
      { icon: "calendar", t: "Planifié et visible", d: "Le prochain live est toujours en évidence, y compris pendant qu'il a lieu." },
      { icon: "chart", t: "Tes repères", d: "Lives tenus par rapport à la semaine précédente et temps de réponse moyen." },
    ],
    faq: [
      { q: "Mes clients ont besoin d'un autre outil de visio ?", a: "Non, ils rejoignent le live depuis leur appli EP Coaching." },
    ],
    related: ["clients", "messages", "formations"],
    help: [],
  },
  {
    slug: "studio",
    group: "business",
    icon: "sparkles",
    name: "Studio créatif",
    for: "Coachs",
    metaTitle: "Studio créatif : écrire, tourner et publier ton contenu de coach",
    metaDesc: "Scripts de reels, vidéos YouTube, posts LinkedIn et Threads, prompteur avec caméra, suivi du tournage et de la publication. Le studio de contenu du coach en ligne.",
    title: "Ton contenu, <span class=\"accent\">de l'idée à la publication</span>",
    lead: "Le contenu fait venir tes clients. Le Studio créatif t'aide à l'écrire, à le tourner et à le publier, puis à voir ce qu'il a rapporté.",
    summary: "Scripts, prompteur avec caméra, tournage et publication suivis.",
    points: [
      { icon: "note", t: "Scripts par plateforme", d: "Instagram, TikTok, YouTube, Facebook, LinkedIn, Threads : chaque script est rangé par plateforme, avec sa description et son appel à l'action." },
      { icon: "video", t: "Prompteur avec caméra", d: "Le prompteur enchaîne tes scripts prêts à tourner et peut enregistrer directement." },
      { icon: "clipboard", t: "Tourné, posté, mesuré", d: "Tu marques « J'ai tourné » puis « J'ai posté », et tu relies la publication à ses chiffres." },
      { icon: "search", t: "Filtres et relances", d: "Filtres par statut, plateforme et pilier, et un rappel quand les scripts à tourner s'accumulent." },
    ],
    stepsTitle: "Le circuit d'un contenu",
    steps: [
      { t: "Écrire", d: "Crée un script, la plateforme se choisit une fois pour toutes." },
      { t: "Tourner", d: "Lance le prompteur : il enchaîne tes scripts, du plus ancien au plus récent." },
      { t: "Publier et mesurer", d: "Marque la publication, puis relie-la dans Mes stats réseaux pour voir ce qu'elle a donné." },
    ],
    faq: [
      { q: "Le Studio publie-t-il à ma place ?", a: "Non. Tu publies toi-même sur tes réseaux, le Studio prépare et suit tout le reste." },
      { q: "Et pour LinkedIn ou Threads ?", a: "Pour le contenu écrit, pas de prompteur : le post est prêt à copier-coller." },
    ],
    related: ["stats-reseaux", "notes", "formations"],
    help: ["ecrire-et-tourner"],
  },
  {
    slug: "stats-reseaux",
    group: "business",
    icon: "chart",
    name: "Stats réseaux",
    for: "Coachs",
    metaTitle: "Stats Instagram, TikTok et YouTube pour coach : ce qui marche vraiment",
    metaDesc: "Note tes chiffres chaque semaine, relie chaque publication à son script et vois ce qui marche : format, jour, heure, et les leads captés par publication.",
    title: "Savoir ce qui marche, <span class=\"accent\">publication par publication</span>",
    lead: "Des vues, c'est bien. Des clients, c'est mieux. Mes stats réseaux relie chaque publication à son script et aux leads qu'elle a vraiment apportés.",
    summary: "Tes chiffres, tes publications et les leads qu'elles apportent.",
    points: [
      { icon: "chart", t: "Chiffres de la semaine", d: "Abonnés, vues, portée : le bouton « Où trouver ces chiffres ? » t'indique où les lire dans chaque appli." },
      { icon: "note", t: "Publication reliée au script", d: "Chaque publication peut être reliée au script du Studio qui l'a produite." },
      { icon: "target", t: "Leads par publication", d: "Les leads captés sur le guide lié à ton script remontent directement sur la publication." },
      { icon: "sparkles", t: "Ce qui marche", d: "Format, jour, heure : l'appli fait ressortir ce qui performe chez toi, et ton objectif d'abonnés avec sa date." },
    ],
    faq: [
      { q: "Faut-il connecter mes comptes ?", a: "Non, tu peux saisir tes chiffres toi-même chaque semaine en quelques minutes." },
    ],
    related: ["studio", "pilotage", "mailing"],
    help: ["suivre-ses-stats"],
  },
  {
    slug: "pilotage",
    group: "business",
    icon: "briefcase",
    name: "Pilotage business",
    for: "Coachs",
    metaTitle: "Pilotage business du coach : ventes, leads, publicité et comptabilité",
    metaDesc: "Non-négociables du jour, stats hebdo, appels de vente, leads, publicité, revenus et dépenses, masterclass business : tout le pilotage d'un coach en ligne.",
    title: "Ton business, <span class=\"accent\">piloté comme une entreprise</span>",
    lead: "Être bon coach ne suffit pas. Le pilotage te donne les chiffres qui comptent chaque semaine et les outils pour construire ton entreprise.",
    summary: "Non-négociables, appels de vente, leads, publicité et compta.",
    points: [
      { icon: "target", t: "Non-négociables et stats hebdo", d: "Les actions quotidiennes qui font avancer ton business, et tes chiffres de la semaine par catégorie." },
      { icon: "users", t: "Appels de vente et leads", d: "Appels bookés, présents, closés, chiffre d'affaires : et un pipeline pour suivre chaque lead avec son statut et sa note." },
      { icon: "chart", t: "Publicité", d: "Tu reportes les chiffres de tes campagnes : coût par lead, taux de clic et retour sur dépense publicitaire sont calculés pour toi." },
      { icon: "briefcase", t: "Revenus et dépenses", d: "Ta comptabilité d'activité, avec l'import des paiements de tes clients." },
      { icon: "book", t: "Hub business et masterclass", d: "Objectifs, feuille de route, modèle économique, funnel, réseau, et des tutoriels pas à pas avec un résultat concret à produire." },
      { icon: "note", t: "Documents", d: "Modèles, contrats types et fichiers de ton activité, rangés au même endroit." },
    ],
    faq: [
      { q: "Je débute, c'est trop pour moi ?", a: "Non : Mon appli masque ce qui ne te sert pas encore. Les masterclass partent de zéro." },
    ],
    related: ["stats-reseaux", "mailing", "equipe"],
    help: ["premiers-pas-coach"],
  },
  {
    slug: "mailing",
    group: "business",
    icon: "mail",
    name: "Mailing",
    for: "Coachs",
    metaTitle: "Mailing pour coach sportif : newsletter, relances et modèles d'email",
    metaDesc: "Envoie ta newsletter, annonce un contenu ou un live, relance un client. Une centaine de modèles d'email, l'envoi à une personne ou à un groupe, et les taux d'ouverture.",
    title: "Tes emails, <span class=\"accent\">sans outil de plus</span>",
    lead: "Newsletter, annonce d'un live, relance d'un client : tu écris depuis l'appli, à une personne ou à tout un groupe, et tu vois qui a ouvert.",
    summary: "Newsletter, annonces, relances et modèles, avec ouvertures et clics.",
    points: [
      { icon: "mail", t: "Une centaine de modèles", d: "Relance, annonce, bienvenue, suivi : pars d'un modèle et adapte-le." },
      { icon: "users", t: "À une personne ou à un groupe", d: "Un email individuel ou un envoi à tes clients actifs." },
      { icon: "chart", t: "Ouvertures et clics", d: "Le taux d'ouverture et de clic de chaque campagne." },
    ],
    faq: [
      { q: "Il me faut un compte d'emailing à part ?", a: "Non, l'envoi passe par l'appli." },
    ],
    related: ["pilotage", "clients", "stats-reseaux"],
    help: [],
  },
  {
    slug: "equipe",
    group: "business",
    icon: "users",
    name: "Équipe et paie",
    for: "Coachs avec une équipe",
    metaTitle: "Gérer une équipe de coaching : coachs, setters, closers et paie",
    metaDesc: "Invite des coachs, donne un espace métier à ton setter, ton closer ou ton monteur, et laisse l'appli calculer la paie du mois à partir des vraies ventes.",
    title: "Ton équipe, <span class=\"accent\">et sa paie calculée seule</span>",
    lead: "Quand tu passes de coach solo à entreprise, EP Coaching suit : chaque membre de l'équipe a son espace, et la paie se calcule à partir des vraies ventes et livraisons.",
    summary: "Coachs, espaces métier, contrats et paie du mois calculée.",
    points: [
      { icon: "users", t: "Invite ton équipe", d: "Des coachs par email, ou un accès métier (setter, closer, monteur et d'autres) avec un espace adapté à chaque poste." },
      { icon: "briefcase", t: "Un espace par métier", d: "Tâches, rendez-vous, prospects, livrables : chaque poste a ses outils, sa messagerie d'équipe et son parcours de formation." },
      { icon: "chart", t: "Paie calculée", d: "Fixe, commissions, paiement à la pièce : la rémunération de chacun se règle en un geste et le mois se calcule tout seul." },
      { icon: "note", t: "Contrats et documents", d: "Contrats par poste et documents d'équipe centralisés." },
    ],
    stepsTitle: "Monter ton équipe",
    steps: [
      { t: "Choisis ton parcours", d: "Dans Mon équipe, choisis « Mon entreprise, avec une équipe »." },
      { t: "Invite", d: "Des coachs par email, ou des accès métier." },
      { t: "Règle la paie", d: "La rémunération de chacun, une fois. Chaque mois, le calcul se fait à partir des ventes et livraisons réelles." },
    ],
    faq: [
      { q: "Mes coachs voient-ils les clients des autres ?", a: "Non, chaque coach ne voit que ses propres clients." },
      { q: "Combien vais-je devoir payer mon closer ce mois-ci ?", a: "Tape « paie » dans la loupe : le montant du mois s'affiche." },
    ],
    related: ["pilotage", "clients", "recherche"],
    help: ["monter-son-equipe"],
  },
];

export const FEATURE_BY_SLUG = Object.fromEntries(FEATURES.map((f) => [f.slug, f]));
