// Centre d'aide : des articles courts, pas à pas, qui décrivent l'appli telle
// qu'elle est (chemins de menus réels). Même règles que le reste du site :
// tutoiement, aucun tiret long, aucun prix.

export const HELP_CATEGORIES = [
  { id: "demarrer", icon: "bolt", title: "Bien démarrer", intro: "Créer ton compte, installer l'appli, la régler à ta façon." },
  { id: "compte", icon: "lock", title: "Compte et confidentialité", intro: "Connexion, email, export et suppression de tes données." },
  { id: "suivi", icon: "clipboard", title: "Suivi, entraînement et nutrition", intro: "Bilan, séances, repas, photos et check-in." },
  { id: "organisation", icon: "calendar", title: "Agenda, notes et recherche", intro: "Organiser tes journées et tout retrouver." },
  { id: "coachs", icon: "users", title: "Pour les coachs", intro: "Clients, contenu, formations, équipe et business." },
  { id: "paiement", icon: "briefcase", title: "Abonnement et facturation", intro: "Paiements, factures et résiliation." },
  { id: "depannage", icon: "help", title: "Dépannage", intro: "Quand quelque chose ne marche pas comme prévu." },
];

export const HELP_ARTICLES = [
  // ── Bien démarrer ───────────────────────────────────────────────────
  {
    slug: "creer-son-compte",
    cat: "demarrer",
    title: "Créer ton compte EP Coaching",
    desc: "Comment créer ton compte gratuit sur EP Coaching, comme membre ou comme coach, en moins d'une minute.",
    intro: "L'inscription est gratuite et ne demande pas de carte bancaire. Tu choisis simplement si tu viens pour toi (membre) ou pour coacher (coach).",
    steps: [
      "Va sur la page d'inscription de l'appli : l'espace membre si tu veux te suivre toi-même ou être coaché, l'espace coach si tu accompagnes des clients.",
      "Renseigne ton email et un mot de passe, puis valide.",
      "Confirme ton adresse depuis l'email que tu reçois.",
      "Réponds aux quelques questions d'accueil (objectif, niveau) : l'appli se règle sur tes réponses.",
    ],
    tips: ["Un coach t'a envoyé un lien d'invitation ? Utilise ce lien : ton compte arrive directement dans son espace."],
    cta: { label: "Créer mon compte", href: "LINK:signupMember" },
    related: ["premiers-pas-membre", "premiers-pas-coach", "installer-lappli"],
  },
  {
    slug: "premiers-pas-membre",
    cat: "demarrer",
    title: "Tes premiers pas dans l'appli (membre)",
    desc: "Les 5 écrans à connaître pour bien démarrer sur EP Coaching : Aujourd'hui, Training, Suivi, Coach et Plus.",
    intro: "L'appli tient en cinq onglets en bas de l'écran. Voici à quoi sert chacun, pour que tu t'y retrouves dès le premier jour.",
    steps: [
      "<strong>Aujourd'hui</strong> : ce que tu as à faire aujourd'hui (bilan, repas, séance). Coche au fur et à mesure.",
      "<strong>Training</strong> : ton programme et ton logbook. Lance ta séance, note tes charges, bats tes records.",
      "<strong>Suivi</strong> : ton bilan du jour, ta nutrition, ta semaine, tes photos et ta progression.",
      "<strong>Coach</strong> : tes messages et ton check-in, si tu es accompagné.",
      "<strong>Plus</strong> : notes, formations, communauté, réglages. Et la loupe, qui trouve tout : tape « poids » ou « calories ».",
    ],
    tips: ["Une visite guidée s'affiche à ta première connexion. Tu peux la relancer depuis Plus, Aide et tutoriels."],
    related: ["remplir-son-bilan", "choisir-ses-suivis", "installer-lappli"],
  },
  {
    slug: "premiers-pas-coach",
    cat: "demarrer",
    title: "Tes premiers pas dans l'appli (coach)",
    desc: "Bien démarrer comme coach sur EP Coaching : Aujourd'hui, Clients, Business, Moi et Plus.",
    intro: "Tout ton business de coach est au même endroit : tes clients, ton contenu, tes ventes, ton équipe et ton propre suivi. Voici l'essentiel en cinq écrans.",
    steps: [
      "<strong>Aujourd'hui</strong> : ton point de départ chaque matin. Alertes clients, ta journée, tes messages non lus et tes raccourcis.",
      "<strong>Clients</strong> : chaque client avec ses bilans, son programme, sa nutrition et vos échanges. Les priorités te disent qui a besoin de toi en premier.",
      "<strong>Business</strong> : Studio pour écrire et tourner tes contenus, stats réseaux, formations, appels de vente, équipe et pilotage.",
      "<strong>Moi</strong> : ton propre suivi (bilan, nutrition, agenda, programme), avec les mêmes outils que tes clients.",
      "<strong>Plus</strong> : notes, bibliothèque, communauté et réglages. La loupe trouve tout : tape « leads » ou le nom d'un client.",
    ],
    tips: ["Commence par Mon appli (dans Plus) : réponds aux questions sur ta façon de travailler, et l'appli masque ce qui ne te sert pas encore."],
    cta: { label: "Créer mon espace coach", href: "LINK:signupCoach" },
    related: ["inviter-ses-clients", "choisir-ses-suivis", "repondre-aux-bilans"],
  },
  {
    slug: "installer-lappli",
    cat: "demarrer",
    title: "Installer l'appli sur ton téléphone",
    desc: "Comment installer EP Coaching sur l'écran d'accueil de ton iPhone ou de ton téléphone Android, sans passer par un store.",
    intro: "EP Coaching s'installe directement depuis ton navigateur. Une fois sur ton écran d'accueil, elle s'ouvre comme une appli classique, en plein écran.",
    steps: [
      "<strong>iPhone</strong> : ouvre le site de l'appli dans Safari, touche le bouton Partager puis « Sur l'écran d'accueil ».",
      "<strong>Android</strong> : ouvre le site de l'appli dans Chrome, touche le menu en haut à droite puis « Installer l'application ».",
      "Ouvre ensuite EP Coaching depuis ton écran d'accueil.",
    ],
    tips: [
      "Sur iPhone, l'installation sur l'écran d'accueil est nécessaire pour recevoir les notifications.",
      "Appui long sur l'icône : tu accèdes directement à la note rapide, au bilan, à l'agenda ou à la recherche.",
    ],
    related: ["activer-les-notifications", "premiers-pas-membre", "notifications-ne-marchent-pas"],
  },
  {
    slug: "choisir-ses-suivis",
    cat: "demarrer",
    title: "Garder seulement ce qui te sert (Mon appli)",
    desc: "Personnalise EP Coaching avec Mon appli : choisis ce que tu suis (poids, sommeil, pas, mensurations...) et masque le reste.",
    intro: "Tout le monde ne suit pas la même chose. Mon appli te pose quelques questions et adapte le menu, ton bilan et ton accueil à tes réponses.",
    steps: [
      "Ouvre Plus, puis Mon appli.",
      "Réponds aux questions : ce que tu suis (poids, mensurations, sommeil, pas, forme du jour...), et ta façon de travailler si tu es coach.",
      "Valide : le menu, ton bilan et ton accueil ne gardent que ce que tu as choisi.",
    ],
    tips: ["Tu peux revenir sur tes choix à tout moment. Rien n'est supprimé, les rubriques sont simplement masquées."],
    related: ["remplir-son-bilan", "premiers-pas-membre", "accessibilite"],
  },
  {
    slug: "activer-les-notifications",
    cat: "demarrer",
    title: "Activer les notifications",
    desc: "Active les notifications d'EP Coaching (bilan, séance, agenda) et règle tes heures de silence pour ne jamais être dérangé la nuit.",
    intro: "Les notifications te rappellent ton bilan, ta séance et les blocs de ton agenda. Tu gardes la main sur les heures où tu ne veux rien recevoir.",
    steps: [
      "Va dans Plus, puis Paramètres.",
      "Active les notifications et accepte la demande de ton téléphone.",
      "Règle tes heures de silence pour ne jamais être dérangé la nuit.",
    ],
    tips: ["Sur iPhone, installe d'abord l'appli sur ton écran d'accueil : c'est la condition pour recevoir les notifications."],
    related: ["installer-lappli", "notifications-ne-marchent-pas", "reorganiser-sa-journee"],
  },

  // ── Compte ──────────────────────────────────────────────────────────
  {
    slug: "mot-de-passe-oublie",
    cat: "compte",
    title: "Mot de passe oublié",
    desc: "Réinitialise ton mot de passe EP Coaching en quelques secondes depuis la page de connexion.",
    intro: "Ça arrive à tout le monde. Tu peux choisir un nouveau mot de passe depuis la page de connexion.",
    steps: [
      "Sur la page de connexion, touche « Mot de passe oublié ».",
      "Saisis l'email de ton compte.",
      "Ouvre l'email reçu et choisis un nouveau mot de passe.",
    ],
    tips: ["Rien reçu ? Regarde dans tes spams, puis vérifie que tu utilises bien l'email de ton compte."],
    cta: { label: "Aller à la connexion", href: "LINK:login" },
    related: ["changer-son-email", "contacter-assistance"],
  },
  {
    slug: "changer-son-email",
    cat: "compte",
    title: "Changer ton adresse email",
    desc: "Comment modifier l'adresse email de ton compte EP Coaching depuis les paramètres.",
    intro: "Ton email sert à te connecter et à recevoir tes rappels. Tu peux le changer toi-même.",
    steps: [
      "Va dans Plus, puis Paramètres.",
      "Touche « Changer mon email » et saisis ta nouvelle adresse.",
      "Confirme le changement depuis l'email reçu sur la nouvelle adresse.",
    ],
    related: ["mot-de-passe-oublie", "exporter-ses-donnees"],
  },
  {
    slug: "exporter-ses-donnees",
    cat: "compte",
    title: "Exporter tes données",
    desc: "Télécharge une copie de tes données EP Coaching depuis les paramètres de ton compte.",
    intro: "Tes données t'appartiennent. Tu peux en télécharger une copie quand tu veux.",
    steps: [
      "Va dans Plus, puis Paramètres.",
      "Touche « Exporter mes données ».",
      "Le fichier se télécharge sur ton appareil.",
    ],
    related: ["supprimer-son-compte", "confidentialite-membre"],
  },
  {
    slug: "supprimer-son-compte",
    cat: "compte",
    title: "Supprimer ton compte",
    desc: "Comment supprimer définitivement ton compte EP Coaching et tes données depuis les paramètres.",
    intro: "Tu peux supprimer ton compte toi-même, sans passer par personne. La suppression est définitive.",
    steps: [
      "Si tu veux garder une trace, commence par exporter tes données.",
      "Va dans Plus, puis Paramètres.",
      "Touche « Supprimer mon compte » et confirme.",
    ],
    tips: ["Si tu as un abonnement en cours, pense à le résilier : écris via la page Assistance en précisant l'email de ton compte."],
    related: ["exporter-ses-donnees", "abonnement-et-facturation"],
  },
  {
    slug: "confidentialite-membre",
    cat: "compte",
    title: "Tes réglages de confidentialité",
    desc: "Qui voit quoi sur EP Coaching, et comment te retirer du classement de la communauté.",
    intro: "Par défaut, tes données de suivi ne sont visibles que par toi, et par ton coach si tu es accompagné. Quelques réglages te permettent d'aller plus loin.",
    steps: [
      "Va dans Plus, puis Paramètres, rubrique Confidentialité.",
      "Retire-toi du classement de la communauté si tu ne veux pas y apparaître.",
      "Tes photos de progression restent privées dans tous les cas.",
    ],
    related: ["exporter-ses-donnees", "supprimer-son-compte"],
    extraLink: { label: "Sécurité et données chez EP Coaching", href: "/securite/" },
  },

  // ── Suivi ───────────────────────────────────────────────────────────
  {
    slug: "remplir-son-bilan",
    cat: "suivi",
    title: "Remplir ton bilan du jour",
    desc: "Le bilan du jour EP Coaching en pratique : poids et nuit le matin, pas, ressenti et nutrition le soir. Et comment rattraper un jour oublié.",
    intro: "Le bilan prend 30 secondes. C'est lui qui donne des données fiables à ton suivi, et à ton coach si tu en as un.",
    steps: [
      "Le matin : ton poids et ta nuit.",
      "Le soir : tes pas, ton ressenti et ta nutrition.",
      "Tes calories viennent toutes seules du tracker nutrition, pas besoin de les retaper.",
    ],
    tips: [
      "Tu as oublié un jour ? Choisis la date en haut du bilan pour le rattraper.",
      "Pèse-toi le matin, après être passé aux toilettes et avant de manger : c'est ce qui rend tes mesures comparables.",
    ],
    related: ["choisir-ses-suivis", "suivre-sa-nutrition", "check-in-hebdo"],
  },
  {
    slug: "suivre-sa-nutrition",
    cat: "suivi",
    title: "Suivre ta nutrition",
    desc: "Valider tes repas prévus, les remplacer, ajouter un aliment ou une recette : le tracker nutrition EP Coaching pas à pas.",
    intro: "Le tracker part de ton plan : tes repas du jour sont déjà proposés. Tu valides, tu remplaces si besoin.",
    steps: [
      "Ouvre Suivi, puis Nutrition.",
      "Un repas mangé comme prévu : valide-le en un geste.",
      "Autre chose : cherche l'aliment ou la recette et ajoute-le. Les choix peuvent se filtrer selon ton régime.",
      "Tes totaux du jour remontent dans ton bilan.",
    ],
    related: ["remplir-son-bilan", "lancer-sa-seance"],
  },
  {
    slug: "lancer-sa-seance",
    cat: "suivi",
    title: "Lancer et noter ta séance",
    desc: "Lancer ta séance du jour dans EP Coaching, noter tes charges série par série et gérer ton temps de repos.",
    intro: "Ta séance est prête dans Training. L'appli te guide exercice par exercice et garde tout.",
    steps: [
      "Ouvre Training : la séance du jour est en haut, avec le matériel à prévoir.",
      "Lance la séance. Pour chaque série, note la charge et les répétitions : la dernière séance est affichée à côté.",
      "Le temps de repos démarre seul et ne bloque jamais l'écran.",
      "Termine la séance : elle rejoint ton historique.",
    ],
    tips: ["Séance terminée par erreur ? Tu peux la rouvrir depuis le logbook."],
    related: ["records-et-historique", "remplir-son-bilan"],
  },
  {
    slug: "records-et-historique",
    cat: "suivi",
    title: "Retrouver tes records et ton historique",
    desc: "Où voir tes records personnels et l'historique complet de tes séances dans EP Coaching.",
    intro: "Chaque série que tu notes est gardée. Tes records sont repérés automatiquement.",
    steps: [
      "Ouvre Training, puis Logbook.",
      "Choisis un exercice pour voir son historique complet et ton record.",
      "Tape « séances » dans la loupe pour voir ton volume de la semaine.",
    ],
    related: ["lancer-sa-seance", "trouver-une-info"],
  },
  {
    slug: "prendre-ses-photos",
    cat: "suivi",
    title: "Prendre tes photos de progression",
    desc: "Bien prendre tes photos de progression et tes mensurations dans EP Coaching pour comparer ce qui est comparable.",
    intro: "Des photos prises dans les mêmes conditions valent plus que n'importe quelle pesée. L'appli te guide pose par pose.",
    steps: [
      "Ouvre Suivi, puis Photos.",
      "Suis les poses proposées, toujours dans la même lumière et à la même distance.",
      "Ajoute tes mensurations si tu les suis.",
      "Compare avec tes photos précédentes, côte à côte.",
    ],
    tips: ["Tes photos sont privées. Seul ton coach, si tu en as un, peut les voir."],
    related: ["remplir-son-bilan", "confidentialite-membre"],
  },
  {
    slug: "check-in-hebdo",
    cat: "suivi",
    title: "Envoyer ton check-in de la semaine",
    desc: "Le check-in hebdomadaire EP Coaching : ta semaine résumée, envoyée à ton coach, qui te répond dans l'appli.",
    intro: "Si tu es accompagné, le check-in est le rendez-vous de la semaine avec ton coach.",
    steps: [
      "Ouvre Coach, puis Check-in.",
      "Relis la revue de ta semaine, affichée au-dessus du formulaire.",
      "Réponds aux questions et envoie.",
      "Ton coach te répond directement dans l'appli.",
    ],
    tips: ["La revue de la semaine (Ma semaine) est ouverte à tous les membres, même sans coach."],
    related: ["remplir-son-bilan", "trouver-un-coach"],
  },
  {
    slug: "trouver-un-coach",
    cat: "suivi",
    title: "Être accompagné par un coach",
    desc: "Comment passer du suivi en autonomie à un accompagnement par un coach sur EP Coaching.",
    intro: "L'appli est gratuite en autonomie. Quand tu veux quelqu'un qui bosse avec toi, tu peux rejoindre un coach.",
    steps: [
      "Tu as reçu un lien d'invitation d'un coach : ouvre-le et crée ton compte, tu arrives directement dans son espace.",
      "Sinon, parcours l'annuaire des coachs et choisis celui qui te correspond.",
      "Tu peux aussi réserver un appel pour l'accompagnement physique de Santamaria Sanchéz.",
    ],
    cta: { label: "Voir l'accompagnement physique", href: "/physique/" },
    related: ["check-in-hebdo", "creer-son-compte"],
    extraLink: { label: "Annuaire des coachs", href: "LINK:coachDirectory" },
  },

  // ── Organisation ────────────────────────────────────────────────────
  {
    slug: "reorganiser-sa-journee",
    cat: "organisation",
    title: "Réorganiser ta journée en retard",
    desc: "Un bloc d'agenda a sauté ? Décale-le ou commence maintenant : toute la suite de ta journée suit, sans toucher à ta semaine type.",
    intro: "Une journée ne se passe jamais comme prévu. L'agenda suit ta vraie journée, pas l'inverse.",
    steps: [
      "Ouvre ton agenda et touche le bloc qui a sauté.",
      "Choisis « Commencer maintenant » ou décale de 15, 30 ou 60 minutes : toute la suite de la journée suit.",
      "« Aujourd'hui seulement » ne touche pas à ta semaine type.",
      "Le bouton en haut de la fiche t'emmène directement au bon endroit (repas, séance, scripts).",
    ],
    related: ["activer-les-notifications", "prendre-des-notes"],
  },
  {
    slug: "prendre-des-notes",
    cat: "organisation",
    title: "Tout noter et tout retrouver",
    desc: "Utiliser les notes EP Coaching : écrire ou dicter, ajouter des #tags, relier des notes avec [[liens]], retrouver tout avec la recherche.",
    intro: "Les notes sont faites pour aller vite : tu notes maintenant, tu ranges jamais, tu retrouves toujours.",
    steps: [
      "Dans Notes, écris ou dicte ton idée, colle un lien ou ajoute une capture d'écran.",
      "Ajoute des #tags (#reel, #client, #idée) : les notes se rangent seules, et une note qui parle d'un tag existant le reçoit automatiquement.",
      "Relie deux notes avec [[Titre de la note]].",
      "La recherche retrouve tout, même depuis la loupe.",
    ],
    tips: ["Le bouton de note rapide est disponible partout dans l'appli."],
    related: ["relier-claude-et-notion", "trouver-une-info"],
  },
  {
    slug: "relier-claude-et-notion",
    cat: "organisation",
    title: "Relier Claude et Notion à tes notes",
    desc: "Ajoute EP Coaching comme connecteur personnalisé dans Claude pour importer tes pages Notion et chercher dans tes notes depuis une conversation.",
    intro: "Le connecteur permet à Claude d'ajouter des notes, de chercher dedans et de lire tes chiffres de la semaine.",
    steps: [
      "Dans Notes, ouvre « Relier Claude et Notion » et génère ton adresse de connecteur.",
      "Sur claude.ai : Réglages, Connecteurs, Ajouter un connecteur personnalisé, puis colle l'adresse.",
      "Dans une conversation, active EP Coaching (et Notion).",
      "Demande par exemple : « importe ma page Notion Idées dans mes notes EP Coaching ».",
    ],
    tips: ["Ton adresse de connecteur est personnelle. Révoque-la dans Notes si tu veux couper l'accès."],
    related: ["prendre-des-notes", "trouver-une-info"],
  },
  {
    slug: "trouver-une-info",
    cat: "organisation",
    title: "Trouver une info en un geste",
    desc: "La loupe d'EP Coaching affiche tout de suite ton poids, tes calories, tes séances, et côté coach tes leads ou la paie de ton équipe.",
    intro: "Pas besoin de savoir dans quel menu se cache une info : tape un mot dans la loupe.",
    steps: [
      "Touche la loupe (en bas à droite, ou en haut de Plus). Sur ordinateur : Ctrl+K ou Cmd+K.",
      "Tape un mot : « poids », « calories », « sommeil », « séances ». Côté coach aussi « clients », « bilans », « leads », « paie ».",
      "Le chiffre s'affiche tout de suite. Touche-le pour ouvrir le détail.",
    ],
    related: ["prendre-des-notes", "records-et-historique"],
  },
  {
    slug: "accessibilite",
    cat: "organisation",
    title: "Taille du texte et animations",
    desc: "Agrandis le texte ou réduis les animations d'EP Coaching dans la rubrique Accessibilité des paramètres.",
    intro: "L'appli s'adapte à ta lecture : tu peux agrandir le texte et limiter les animations.",
    steps: [
      "Va dans Plus, puis Paramètres, rubrique Accessibilité.",
      "Règle la taille du texte.",
      "Réduis les animations si tu préfères un affichage plus calme.",
    ],
    related: ["choisir-ses-suivis", "installer-lappli"],
  },

  // ── Coachs ──────────────────────────────────────────────────────────
  {
    slug: "inviter-ses-clients",
    cat: "coachs",
    title: "Inviter tes clients",
    desc: "Trouve ton lien d'invitation dans les paramètres et envoie-le à tes clients : ils arrivent directement dans ton espace coach.",
    intro: "Chaque coach a son propre lien d'invitation. Un client qui s'inscrit avec ce lien est rattaché à toi automatiquement.",
    steps: [
      "Va dans Plus, puis Paramètres.",
      "Copie « Ton lien d'invitation ».",
      "Envoie-le à ton client (message, email, bio).",
      "Dès son inscription, il apparaît dans tes Clients.",
    ],
    related: ["repondre-aux-bilans", "creer-un-programme", "premiers-pas-coach"],
  },
  {
    slug: "repondre-aux-bilans",
    cat: "coachs",
    title: "Répondre aux bilans de tes clients",
    desc: "La boîte de réception coach d'EP Coaching regroupe bilans, demandes de correction technique et photos en attente, triés par ancienneté.",
    intro: "Plus besoin d'ouvrir chaque fiche client pour savoir ce qui traîne : tout ce qui attend une réponse est au même endroit.",
    steps: [
      "Ouvre Clients, puis Boîte de réception.",
      "Traite les éléments du plus ancien au plus récent : bilans, corrections technique, photos.",
      "Réponds depuis l'élément : ton client reçoit ta réponse dans son appli.",
      "Jette un œil aux Priorités : elles remontent les clients qui décrochent.",
    ],
    related: ["inviter-ses-clients", "creer-un-programme"],
  },
  {
    slug: "creer-un-programme",
    cat: "coachs",
    title: "Créer et assigner un programme",
    desc: "Construire un programme d'entraînement pour un client dans EP Coaching, à partir d'un modèle ou de zéro, et l'assigner.",
    intro: "Les modèles te font gagner du temps : tu construis une base une fois, tu l'adaptes à chaque client.",
    steps: [
      "Ouvre Clients, puis Modèles, pour partir d'un modèle existant ou en créer un.",
      "Adapte les exercices, les séries et les cibles au client. Le référentiel Contraintes et populations t'aide pour une blessure ou une situation particulière.",
      "Assigne le programme depuis la fiche du client.",
      "Le client le retrouve dans Training et ses séances remontent dans sa fiche.",
    ],
    related: ["repondre-aux-bilans", "inviter-ses-clients"],
  },
  {
    slug: "planifier-un-live",
    cat: "coachs",
    title: "Planifier un live",
    desc: "Planifier un appel 1-to-1, un audit, un atelier ou un webinaire dans EP Coaching.",
    intro: "Tes lives se planifient dans l'appli et tes clients les rejoignent depuis leur propre espace.",
    steps: [
      "Ouvre Clients, puis Coaching live.",
      "Choisis le format : 1-to-1, audit, check-in hebdo, accès direct, atelier, webinaire ou questions-réponses.",
      "Choisis la date, l'heure et, pour un format individuel, le client invité.",
      "Le live apparaît dans le bandeau « Prochain live », y compris pendant qu'il a lieu.",
    ],
    related: ["repondre-aux-bilans", "envoyer-un-mailing"],
  },
  {
    slug: "ecrire-et-tourner",
    cat: "coachs",
    title: "Écrire et tourner tes contenus",
    desc: "Le circuit d'un contenu dans le Studio créatif : écrire le script, tourner avec le prompteur, marquer la publication.",
    intro: "Le Studio créatif suit chaque contenu de l'idée à la publication.",
    steps: [
      "Dans Studio, crée un script (la plateforme se choisit une fois pour toutes).",
      "Lance le prompteur : il enchaîne tes scripts prêts à tourner, du plus ancien au plus récent.",
      "Marque « J'ai tourné » puis « J'ai posté ».",
      "Relie la publication dans Mes stats réseaux pour voir ce qu'elle a donné.",
    ],
    tips: ["Pour LinkedIn et Threads, pas de prompteur : le post est prêt à copier-coller."],
    related: ["suivre-ses-stats", "prendre-des-notes"],
  },
  {
    slug: "suivre-ses-stats",
    cat: "coachs",
    title: "Suivre tes stats Instagram, TikTok, YouTube",
    desc: "Note tes chiffres chaque semaine dans Mes stats réseaux et relie tes publications à leurs scripts pour voir ce qui marche.",
    intro: "Quelques minutes par semaine suffisent pour savoir enfin ce qui marche chez toi.",
    steps: [
      "Dans Business, ouvre Mes stats réseaux.",
      "Chaque semaine, note tes chiffres (abonnés, vues, portée). Le bouton « Où trouver ces chiffres ? » t'indique où les lire dans chaque appli.",
      "Ajoute tes publications avec leurs chiffres et relie-les à ton script.",
      "L'appli te montre ce qui marche : format, jour, heure.",
    ],
    related: ["ecrire-et-tourner", "envoyer-un-mailing"],
  },
  {
    slug: "creer-sa-formation",
    cat: "coachs",
    title: "Créer et vendre ta formation",
    desc: "Créer une formation vidéo dans EP Coaching, la donner à tes clients ou la vendre avec ton lien de paiement.",
    intro: "Ta formation est structurée comme un vrai cours, avec des vidéos que tu héberges sur YouTube.",
    steps: [
      "Dans Business, ouvre Mes formations puis « Nouvelle formation ».",
      "Ajoute tes sections et tes vidéos YouTube (même non répertoriées), puis publie.",
      "Choisis « Incluse pour mes clients » ou « Payante » avec ton lien de paiement.",
      "Après un achat, donne l'accès en un clic.",
    ],
    related: ["ecrire-et-tourner", "monter-son-equipe"],
  },
  {
    slug: "envoyer-un-mailing",
    cat: "coachs",
    title: "Envoyer un email à tes clients",
    desc: "Envoyer une newsletter, une annonce ou une relance depuis le Mailing d'EP Coaching, à une personne ou à un groupe.",
    intro: "Pas besoin d'un outil d'emailing à part : tu écris depuis l'appli.",
    steps: [
      "Ouvre Clients, puis Mailing.",
      "Pars d'un modèle (relance, annonce, bienvenue...) ou d'une page blanche.",
      "Choisis les destinataires : une personne ou un groupe.",
      "Envoie, puis suis les ouvertures et les clics.",
    ],
    related: ["planifier-un-live", "suivre-ses-stats"],
  },
  {
    slug: "monter-son-equipe",
    cat: "coachs",
    title: "Recruter et payer ton équipe",
    desc: "Inviter des coachs et des métiers (setter, closer, monteur) dans EP Coaching, et laisser l'appli calculer la paie du mois.",
    intro: "Quand ton activité grandit, ton équipe travaille dans la même appli que toi.",
    steps: [
      "Dans Business, ouvre Mon équipe et choisis « Mon entreprise, avec une équipe ».",
      "Invite des coachs par email, ou donne un accès métier (setter, closer, monteur...) : chacun a un espace adapté.",
      "Règle la rémunération de chacun en un geste.",
      "La paie du mois se calcule seule à partir des vraies ventes et livraisons. Tape « paie » dans la loupe pour la voir.",
    ],
    related: ["creer-sa-formation", "trouver-une-info"],
  },

  // ── Paiement ────────────────────────────────────────────────────────
  {
    slug: "abonnement-et-facturation",
    cat: "paiement",
    title: "Abonnement, factures et résiliation",
    desc: "Comment fonctionnent les paiements sur EP Coaching, où demander une facture et comment résilier un abonnement.",
    intro: "Le suivi en autonomie est gratuit. Les accompagnements et l'espace coach sont payants, et les paiements passent par Stripe, un prestataire de paiement sécurisé.",
    steps: [
      "Pour une facture, un prélèvement ou une résiliation, passe par la page Assistance.",
      "Précise l'email associé à ton compte : ça évite un aller-retour.",
      "Tu reçois une réponse sous 48 heures ouvrées.",
    ],
    tips: ["Les conditions complètes sont dans les Conditions générales de vente."],
    cta: { label: "Ouvrir l'assistance", href: "LINK:support" },
    related: ["supprimer-son-compte", "contacter-assistance"],
    extraLink: { label: "Conditions générales de vente", href: "LINK:cgv" },
  },

  // ── Dépannage ───────────────────────────────────────────────────────
  {
    slug: "appli-ne-se-charge-pas",
    cat: "depannage",
    title: "L'appli ne se charge pas ou affiche une ancienne version",
    desc: "Que faire si EP Coaching ne s'ouvre pas, reste bloquée ou n'affiche pas les dernières nouveautés.",
    intro: "Dans la grande majorité des cas, une vérification rapide suffit.",
    steps: [
      "Vérifie ta connexion internet (Wi-Fi ou données mobiles).",
      "Ferme complètement l'appli, puis rouvre-la.",
      "Toujours bloquée ? Ouvre l'appli dans ton navigateur et recharge la page.",
      "En dernier recours, supprime l'icône de ton écran d'accueil et réinstalle l'appli : tes données restent sur ton compte.",
    ],
    related: ["installer-lappli", "contacter-assistance"],
  },
  {
    slug: "notifications-ne-marchent-pas",
    cat: "depannage",
    title: "Je ne reçois pas les notifications",
    desc: "Les notifications EP Coaching n'arrivent pas ? Les vérifications à faire sur iPhone et Android.",
    intro: "Les notifications dépendent à la fois de l'appli et des réglages de ton téléphone.",
    steps: [
      "Sur iPhone, vérifie que l'appli est bien installée sur ton écran d'accueil et que tu l'ouvres depuis cette icône.",
      "Dans Plus, Paramètres, vérifie que les notifications sont activées. Si besoin, réactive-les.",
      "Dans les réglages de ton téléphone, vérifie que les notifications sont autorisées pour EP Coaching.",
      "Vérifie tes heures de silence : pendant ce créneau, rien n'est envoyé.",
    ],
    related: ["activer-les-notifications", "installer-lappli"],
  },
  {
    slug: "contacter-assistance",
    cat: "depannage",
    title: "Contacter l'assistance",
    desc: "Une question sur ton compte, ton abonnement ou un souci technique ? Voici comment joindre l'assistance EP Coaching.",
    intro: "Une vraie personne te répond, sous 48 heures ouvrées.",
    steps: [
      "Ouvre la page Assistance.",
      "Décris ton souci en une ou deux phrases, avec l'email de ton compte.",
      "Si c'est un bug, précise ton téléphone et ce que tu faisais au moment du problème.",
    ],
    cta: { label: "Ouvrir l'assistance", href: "LINK:support" },
    related: ["appli-ne-se-charge-pas", "abonnement-et-facturation"],
  },
];

export const HELP_BY_SLUG = Object.fromEntries(HELP_ARTICLES.map((a) => [a.slug, a]));
